[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) ğŸŒš "
disabled = false
show_always = true

[hostname]
ssh_only = false
ssh_symbol = 'ğŸŒ '
format = 'on [$hostname](bold yellow) '
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
# Replace the "âœ—" symbol in the prompt with ""
[character]
success_symbol = "[â¯](bold cyan)"
error_symbol = "[âœ—](bold red)"

[directory]
read_only = " â›”"
truncation_length = 10
truncate_to_repo = true
style = "bold italic blue"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic red"

[sudo]
symbol = 'ğŸ§™ '
style = 'bold blue'
disabled = false

[c]
disabled = false

[java]
symbol = 'â˜• '
disabled = false

[python]
symbol = 'ğŸ '
disabled = false

[memory_usage]
symbol = 'ğŸ '
threshold = -1
format = '$symbol[${ram_pct}( | ${swap_pct})]($style) '
disabled = false

[shell]
disabled = false
unknown_indicator = 'unknown shell'

# [time]
# disabled = false
